### ISSUE TITLE
Updated to Core 2.1 and now I get this error: `Application startup exception: System.MissingMethodException: Method not found: 'Void Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.IncludeXmlComments(System.String)'.`

### ISSUE THREAD

**Issue by VictorioBerra** [Dotnet-Boxed/Framework#19]
```
Application startup exception: System.MissingMethodException: Method not found: 'Void Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions.IncludeXmlComments(System.String)'.
   at Boilerplate.AspNetCore.Swagger.SwaggerGenOptionsExtensions.IncludeXmlCommentsIfExists(SwaggerGenOptions options, String filePath)
   at Boilerplate.AspNetCore.Swagger.SwaggerGenOptionsExtensions.IncludeXmlCommentsIfExists(SwaggerGenOptions options, Assembly assembly)
   at WuitCMDB.API.ServiceCollectionExtensions.<>c__DisplayClass8_0.<AddSwagger>b__0(SwaggerGenOptions options) in C:\Source\MyApp\ServiceCollectionExtensions.cs:line 192
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.SwaggerGenServiceCollectionExtensions.CreateSwaggerProvider(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.Internal.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
DevConf [17:30:16 Fatal] Microsoft.AspNetCore.Hosting.Internal.WebHost
```

**Comment by VictorioBerra** [comment]
I removed `Boilerplate.AspNetCore` and `Boilerplate.AspNetCore.Swagger` and installed `Boxed.AspNetCore` and `Boilerplate.AspNetCore.Swagger` this did not solve my issue.

**Comment by VictorioBerra** [comment]
Is it possible this broke it? I also updated Swashbuckle.AspNetCore to 2.5.0 which was recently released.

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/da987073ff212e1ed60b8d0b35798b05fe4cdfe8#diff-9e9ab36196f1a6384a208dffc4a62c32

They added `bool includeControllerXmlComments = false` to `IncludeXmlComments()`. Does that mean you need to pass that argument down here as well? https://github.com/Dotnet-Boxed/Framework/blob/master/Source/Boxed.AspNetCore.Swagger/SwaggerGenOptionsExtensions.cs#L64

**Comment by VictorioBerra** [comment]
Actually, I would wager that means you need to update your version of Swashbuckle.AspNetCore to 2.5.0 https://github.com/Dotnet-Boxed/Framework/blob/master/Source/Boxed.AspNetCore.Swagger/Boxed.AspNetCore.Swagger.csproj#L49.

**Comment by RehanSaeed** [comment]
Yes, I think you are probably right. I'm working on an update for 2.1.

**Comment by RehanSaeed** [comment]
Released a new version. You could also have added the latest. Swashbuckle package to the project yourself.

**Comment by VictorioBerra** [comment]
@RehanSaeed I already have a reference to it in my project, not sure why that did not solve the issue.

**Comment by Salahas** [comment]
I am having this problem now with Swashbuckle.AspNetCore 4.0.1
And if I downgrade I get failed to load API definition. internal server error /swagger/v1/swagger.json
Any ideas!!

**Comment by RehanSaeed** [comment]
Have you also upgraded the `Swashbuckle.AspNetCore` package to `4.0.1`?

**Comment by Salahas** [comment]
@RehanSaeed Yes, I did that.

**Comment by RehanSaeed** [comment]
Is this with an existing project that you've upgraded or with a brand new one? If existing, then create a new project and compare your code.

**Comment by RehanSaeed** [comment]
@ranouf The project template has no problem running ASP.NET Core 2.1.6 with Swashbuckle 4.0.1. You are not using `Boxed.AspNetCore.Swagger`, so there is no problem there. Perhaps it would make sense to post an issue in the Swashbuckle repo?

**Comment by ranouf** [comment]
@RehanSaeed This is a really good point! :) I m clearly not at the good place :)
