### ISSUE TITLE
app.UseHttpException(); throws

### ISSUE THREAD

**Issue by olivereisenhut** [Dotnet-Boxed/Framework#196]
### Describe the bug

The package throws an unhandled exception when adding exception middleware with app.UseHttpException();. Just happens on with 5.* versions.

```
System.NotSupportedException: Types that implement 'Microsoft.AspNetCore.Http.IMiddleware' do not support explicit arguments.
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.UseMiddleware(IApplicationBuilder app, Type middleware, Object[] args)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.UseMiddleware[TMiddleware](IApplicationBuilder app, Object[] args)
   at Boxed.AspNetCore.ApplicationBuilderExtensions.UseHttpException(IApplicationBuilder application, Action`1 configureOptions)
   at Boxed.AspNetCore.ApplicationBuilderExtensions.UseHttpException(IApplicationBuilder application)
   at bla.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in /Users/oeisenhut/Projects/playground/bla/Startup.cs:line 40
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at bla.Program.Main(String[] args) in /Users/oeisenhut/Projects/playground/bla/Program.cs:line 16
```

### To Reproduce

1. Create new api `dotnet new webapi`
2. Add `Boxed.AspNetCore` Nuget package with version >= 5
3. Add `app.UseHttpException();` to Startup.cs
```
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpException();
            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

        }
```
4. Start the app.
5. See the exception

### Expected behaviour

The api starts without throwing an exception.

**Comment by RehanSaeed** [comment]
Not supporting version 5 yet. Will do so when it's released in a few months.
